### ISSUE TITLE
Enhance report by unit under test

### ISSUE THREAD

**Issue by SamuelMelm** [HMS-Analytical-Software/SASUnit#2]
[This report](http://sasunit.sourceforge.net/rep/auton_overview.html) should list for every unit under test all the test scenarios and, within them, all the test cases where the respective unit under test is being used. Maybe it would be better to have a separate page per unit under test. 

Also it should be considered to allow for more than one unit under test per test case because often more than one test candidate is being used in a test. This would give a better overview of test coverage. 

Ideally, it should not be necessary any longer to specify the unit(s) under test in the test case. They could be detected by scanning the log of the test case. 

Besides, the column "Test cases" now wrongly shows the number of checks (asserts), not test cases. And NLS is not fully worked through, so the German word "ohne" appears.

---

Originally created on SourceForge by amangold - 12.07.2012, 00:10
```[tasklist]
### Tasks
- [ ] Seperate list per unit under test
- [ ] Allow more than one unit under test per test case
- [ ] No need to specify name of unit under test
- [x] Test cases show number of Assertions
```
